### ISSUE TITLE
Update to version 2.1

### ISSUE THREAD

**Issue by Gungrave223** [Vivastream/spring-security-oauth2-dynamodb#2]
I'm updating an older project and saw that there is an update to support AmazonDynamoDB instead of AmazonDynamoDBClient...but maven is unable to pull back the artifact for v2.1...

Any chance of a getting an update publish.

**Comment by vondruke** [comment]
We don't actually publish this artifact to any public maven repo.   This must have been published to a local/internal repo if this is being used by your project.  Hope this helps!

**Comment by Gungrave223** [comment]
It absolute does thank you.
